Options:
  # enabled - true = enabled, false = disabled. (Default = true)
  enabled: true

  # overworld-prefix - Enter tablist prefix for player in overworld dimension, color codes supported as: &a, &c, etc
  overworld-prefix: '&a'

  # nether-prefix - Enter tablist prefix for player in nether dimension, color codes supported as: &a, &c, etc
  nether-prefix: '&c'

  # end-prefix - Enter tablist prefix for player in end dimension, color codes supported as: &a, &c, etc
  end-prefix: '&d'