Options:
  # Enabled - true = Enabled, false = Disabled. (Default = true)
  Enabled: true
  # Overworld-Prefix - Enter Prefix For Player In Overworld Dimension, Color Codes Supported As: &a, &c, etc
  Overworld-Prefix: '&a'
  # Nether-Prefix - Enter Prefix For Player In Nether Dimension, Color Codes Supported As: &a, &c, etc
  Nether-Prefix: '&c'
  # End-Prefix - Enter Prefix For Player In End Dimension, Color Codes Supported As: &a, &c, etc
  End-Prefix: '&d'
Settings:
  # Check-Delay - How Frequently The Plugin Checks A Player's Dimension. Can Be Adjusted Higher For Better Performance Or Lower For Real-Time Monitoring. Eg: 10 = Checks Every 10 In-Game Ticks.
  Check-Delay: 10