Options:
  # enabled - true = enabled, false = disabled
  enabled: true

  # overworld-prefix & suffix - Enter tablist prefix & suffix for player in OVERWORLD dimension, color codes supported as: &a, &c, etc
  overworld-prefix: '&a'
  overworld-suffix: ''

  # nether-prefix & suffix - Enter tablist prefix & suffix for player in NETHER dimension, color codes supported as: &a, &c, etc
  nether-prefix: '&c'
  nether-suffix: ''

  # end-prefix & suffix - Enter tablist prefix & suffix for player in END dimension, color codes supported as: &a, &c, etc
  end-prefix: '&d'
  end-suffix: ''